### ISSUE TITLE
[7d]Create the first-moble web app to watch Youtube videos with subtitles 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/eLang-tv.com#1]
Description:
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV

**Comment by pavladan** [comment]
Tasklist:

- [ ] [2h] prepare the work area 
- [ ] [4h] add routing between catalog page and video page
- [ ] [6h] add YouTube support and control panel
- [ ] [4h] add YouTube subtitle support and sync display with video
- [ ] [4h] divide subtitles into words and show translation when tapping
- [ ] [6h] add buttons repeat/repeat slowly/next/previous and swipe events

**Comment by KatyaLogosh** [comment]
@pavladan last sketches 
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=0%3A1
