### ISSUE TITLE
[4h]Add a popup about the need for authorization if an unregistered user is trying to add a word to the dictionary

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#105]
Description:
The user doesn't understand what the "+" button is for until they register. 

Solution: make a pop-up about the need to register to add a word to the vocabulary
![image](https://user-images.githubusercontent.com/70699061/96118330-04301080-0ef4-11eb-98cc-9a43b7777c0e.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/96450675-2e007480-121f-11eb-877a-697220800511.png)
![image](https://user-images.githubusercontent.com/58423687/96450715-3c4e9080-121f-11eb-8765-10a08d856441.png)

**Comment by annamaksimik** [comment]
Watch Frame "1366w / eLang-TV / HD / PopUp LoginSignUp"
**Figma/eLang-TV/💻 HD Final [1366 width]**  https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2214%3A24
![image](https://user-images.githubusercontent.com/58423687/96452227-6a34d480-1221-11eb-8350-6622fa977143.png)

Watch Frame "eLang-TV / PopUp LoginSignUp"
**Figma/eLang-TV/📱 Mobile Final**  https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2214%3A390
![image](https://user-images.githubusercontent.com/58423687/96453349-014e5c00-1223-11eb-9d71-9efe0cf0d7cc.png)

**Comment by lllana** [comment]
- [ ] @lllana add events in analytics

**Comment by alexnpol** [comment]
![image](https://user-images.githubusercontent.com/70699061/96727173-7359a900-13bb-11eb-988d-ed9357bc4105.png)
