### ISSUE TITLE
[4h]Create a user flow for the user who opened the eLang TV site

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#108]
Description:
Create a user flow so that we can understand the visual representation of the sequence of actions that users perform to achieve the goal.

**Post the result of the work in Figma and attach the link!**

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/Artifacts?node-id=2%3A2
