### ISSUE TITLE
[5h]Create a user flow for monetization eLangTV

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#110]
Description: 
Create a user flow based on the old scheme (link below).
The scheme includes: 
- a modal window that informs you that you need to register to add a word to the dictionary 
- a modal window that informs you about translation limits (after registration)

 Old scheme https://miro.com/welcomeonboard/j8VVtTKLe400A3p4uY2cycHaCm7H49qzb2qVmYGmchDXv01ZrSL2FSrRqEdybrEX

**Comment by NikaPipchenko** [comment]
https://miro.com/welcomeonboard/qf6NEDfhY76hc0y0AfhQ4fP48LS78A8K5zQcXIA9lnyzFvB1WZLR6Ax4o1xUpkoC
