### ISSUE TITLE
[5h]Create User Flow eLang-Tv

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#113]
Описание:
Сделать ЮФ в виде блок-схемы. ЮФ включает в себя весь функционал eLangTV, все возможные шаги пользователя во всем приложении.

Необходим детальный ЮФ для отслеживания проблемных мест в приложении, в которых отпадают пользователи.

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/Artifacts?node-id=73%3A68

**Comment by alexnpol** [comment]
1. Если пользользователь выберет "Войти или создать аккаунт" (на схеме Регистрация", то на схму нужна стрелочка к окну Регистрации/Авторизации:

![image](https://user-images.githubusercontent.com/70699061/97359527-f09a8780-18ad-11eb-989f-b3afed02e54b.png)

2. После Создания аккаунта у пользователя появляется модалка о успешной регистрации. В ней можно рассказать о лимитах и возможности снять эти лимиты (купить премиум).  модалки пользователь может попасть на стр покупки премиума или на стартовую страницу поиска видео. 
Модалка сейчас на стадии дизайна!
