### ISSUE TITLE
[4h]Create a vocabulary Information architecture

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#117]
Description: Create a schema that allows you to understand what a single vocabulary will look like for all products (Player, eLangTV, Extension)

When ready, attach a link to the document with the diagram

**Comment by NikaPipchenko** [comment]
https://miro.com/welcomeonboard/PVkplQMERzyt1IL43g6dA5coG4MQWbnRk70DQING9tmKc6853iO2tfy4nvJV3pUz
