### ISSUE TITLE
[20h]Add a vocabulary header

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#127]
Description:
The header includes:
- the **main checkbox** that allows you to select all words; 
- **Search bar** that allows you to search for words in the dictionary in Russian and English; 
- **Sorting menu**, with a drop-down list (1. Alphabetically: A-Z, Z-A; 2. Date: Old first, new first). The default option is alphabetically A-Z
- **Main trashcan**. Appears when one of the checkboxes is selected. Allows you to delete the selected word (or several words)

You need to draw intermediate Windows after clicking on the checkbox, clicking on the trash, and so on.

Ancillary materials:
To make the design in accordance with the hierarchy of the website https://miro.com/app/board/o9J_kiKf0s4=/
Example of a vocabulary in the Tutor https://www.figma.com/file/78GiMuG6zyNqscyIR0Rk8K/Vocabulary?node-id=0%3A1
- [x] Is this task clear?

![image](https://user-images.githubusercontent.com/70699061/96427633-7744ca00-1207-11eb-91b6-1b957fbd5e0b.png)

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]

_Watch frames "1366w  / 1.2 Vocabulary / Checkbox", "1366w  / 1.2 Vocabulary / All_Checkbox",  "1366w  / 1.2 Vocabulary / Delete Marked Words", "1366w  / 1.2 Vocabulary / Delete Marked Words / Done", "1366w  / 1.2 Vocabulary / Hover_Word", "1366w  / 1.2 Vocabulary / Sort By", "1366w  / 1.2 Vocabulary / Sort By / Dropdown_open"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2233%3A16771

![image](https://user-images.githubusercontent.com/58423687/96705714-5367bc80-139e-11eb-8f26-7c6a8a94f540.png)


📱 Mobile Final

_Watch frames "1.1 Vocabulary / Sort By", "1.1 Vocabulary / Sort By / Dropdown_open", "1.1 Vocabulary / Checkbox", "1.1 Vocabulary / 1.1.2 Сlick On The Button", "1.1 Vocabulary / 1.1.1 Сlick On The Button", "1.1 Vocabulary / 1.1.2 click on the button Delete", "1.1 Vocabulary / 1.1.1 click on the button Delete", "1.1 Vocabulary / 1.1.2 click on the button Delete / Done", "1.1 Vocabulary / 1.1.1 click on the button Delete / Done"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2274%3A2473

![image](https://user-images.githubusercontent.com/58423687/96705533-1996b600-139e-11eb-8267-ef5e9055e2b6.png)
![image](https://user-images.githubusercontent.com/58423687/96705572-287d6880-139e-11eb-99e3-158c1858d9cd.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final

_Watch frames "1.1 Vocabulary / Sort By", "1.1 Vocabulary / Sort By / Dropdown_open", "1.1 Vocabulary / Checkbox", "1.1 Vocabulary / 1.1.2 Сlick On The Button", "1.1 Vocabulary / 1.1.1 Сlick On The Button", "1.1 Vocabulary / 1.1.2 click on the button Delete", "1.1 Vocabulary / 1.1.1 click on the button Delete", "1.1 Vocabulary / 1.1.2 click on the button Delete / Done", "1.1 Vocabulary / 1.1.1 click on the button Delete / Done"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2274%3A2473

![image](https://user-images.githubusercontent.com/58423687/96705533-1996b600-139e-11eb-8267-ef5e9055e2b6.png)
![image](https://user-images.githubusercontent.com/58423687/96706208-f4567780-139e-11eb-9ad9-52726aebb1d9.png)
