### ISSUE TITLE
 Edit the word list section

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#129]
Add to each word: 
- your own checkbox (1),
- the ability to listen to/play a word (2), 
- a button to delete a single word (4). By default, the trash is gray, and when you hover the cursor over it, it turns red

Translation move closer to the English word (3)

Ancillary materials:
To make the design in accordance with the hierarchy of the website https://miro.com/app/board/o9J_kiKf0s4=/
Example of a vocabulary in the Tutor https://www.figma.com/file/78GiMuG6zyNqscyIR0Rk8K/Vocabulary?node-id=0%3A1

![image](https://user-images.githubusercontent.com/70699061/96429262-6c8b3480-1209-11eb-8f6b-139c42446ceb.png)

**Comment by EugeneShastak** [comment]
- [ ] Add word filtering ability design:
1) New words
2) Words in teaching
3) Learned words

<img width="482" alt="Снимок экрана 2020-10-19 в 16 09 48" src="https://user-images.githubusercontent.com/70751961/96455179-85a1de80-1225-11eb-8bd7-d8323a917f43.png">

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/96557138-88064600-12c2-11eb-85a5-12d4731a16cc.png)

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]

_Watch frames "1366w  / 1.2 Vocabulary / Checkbox", "1366w  / 1.2 Vocabulary / All_Checkbox",  "1366w  / 1.2 Vocabulary / Delete Marked Words", "1366w  / 1.2 Vocabulary / Delete Marked Words / Done", "1366w  / 1.2 Vocabulary / Hover_Word", "1366w  / 1.2 Vocabulary / Sort By", "1366w  / 1.2 Vocabulary / Sort By / Dropdown_open"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2233%3A16771
![image](https://user-images.githubusercontent.com/58423687/96587380-efd08700-12ea-11eb-8c7b-804478865679.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final

_Watch Frames "1.1 Vocabulary / Sort By", "1.1 Vocabulary / Sort By / Dropdown_open", "1.1 Vocabulary / Checkbox", "1.1 Vocabulary / All_Checkbox", "1.1 Vocabulary / Delete Marked Words", "1.1 Vocabulary / Delete Marked Words / Done"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2244%3A19357
![image](https://user-images.githubusercontent.com/58423687/96588463-5a35f700-12ec-11eb-9214-aaa338d6130f.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/96589472-84d47f80-12ed-11eb-926e-6d0abec8b62e.png)

**Comment by alexnpol** [comment]
@annamaksimik внести правки: Если слово активно (стоит галочка в чекбоксе), то, появляется корзина отдельного этого слова. Кликнув на нее, пользователь может удалить слово, к которому относится эта корзина

**Comment by annamaksimik** [comment]
📱 Mobile Final

_Watch frames "1.1 Vocabulary / Sort By", "1.1 Vocabulary / Sort By / Dropdown_open", "1.1 Vocabulary / Checkbox", "1.1 Vocabulary / 1.1.2 Сlick On The Button", "1.1 Vocabulary / 1.1.1 Сlick On The Button", "1.1 Vocabulary / 1.1.2 click on the button Delete", "1.1 Vocabulary / 1.1.1 click on the button Delete", "1.1 Vocabulary / 1.1.2 click on the button Delete / Done", "1.1 Vocabulary / 1.1.1 click on the button Delete / Done"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2274%3A2473

![image](https://user-images.githubusercontent.com/58423687/96696481-7e004800-1393-11eb-82cd-86245e5ccad5.png)
![image](https://user-images.githubusercontent.com/58423687/96696548-8fe1eb00-1393-11eb-974d-0c888ec2a09e.png)

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]

_Watch frames "1366w  / 1.2 Vocabulary / Checkbox", "1366w  / 1.2 Vocabulary / All_Checkbox",  "1366w  / 1.2 Vocabulary / Delete Marked Words", "1366w  / 1.2 Vocabulary / Delete Marked Words / Done", "1366w  / 1.2 Vocabulary / Hover_Word", "1366w  / 1.2 Vocabulary / Sort By", "1366w  / 1.2 Vocabulary / Sort By / Dropdown_open"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2233%3A16771
![image](https://user-images.githubusercontent.com/58423687/96587380-efd08700-12ea-11eb-8c7b-804478865679.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final

_Watch frames "1.1 Vocabulary / Sort By", "1.1 Vocabulary / Sort By / Dropdown_open", "1.1 Vocabulary / Checkbox", "1.1 Vocabulary / 1.1.2 Сlick On The Button", "1.1 Vocabulary / 1.1.1 Сlick On The Button", "1.1 Vocabulary / 1.1.2 click on the button Delete", "1.1 Vocabulary / 1.1.1 click on the button Delete", "1.1 Vocabulary / 1.1.2 click on the button Delete / Done", "1.1 Vocabulary / 1.1.1 click on the button Delete / Done"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2274%3A2473

![image](https://user-images.githubusercontent.com/58423687/96707386-772c0200-13a0-11eb-91ab-794772ddbb40.png)
![image](https://user-images.githubusercontent.com/58423687/96707411-801cd380-13a0-11eb-8249-c8c507560426.png)
