### ISSUE TITLE
[4h] Change the word card in the vocabulary

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#130]
Description:
Add the date of addition, delete button, and listen to the word to the card

Ancillary materials:
To make the design in accordance with the hierarchy of the website https://miro.com/app/board/o9J_kiKf0s4=/
![image](https://user-images.githubusercontent.com/70699061/96435550-677cb400-120e-11eb-88b0-79122afc774d.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final

Watch frames 
"1.1 Vocabulary / OpenWordCard",
"1.1 Vocabulary / OpenWordCard / DeleteWord", 
"1.1 Vocabulary / OpenWordCard / DeleteWord / ButtonDelete", 
"1.1 Vocabulary / OpenWordCard / DeleteWord / Done"

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2295%3A16103

![image](https://user-images.githubusercontent.com/58423687/96730368-c123e080-13be-11eb-9f2b-d10ff5dab4b4.png)
![image](https://user-images.githubusercontent.com/58423687/96730393-c84aee80-13be-11eb-84b9-4b109714de7b.png)

**Comment by alexnpol** [comment]
@annamaksimik добавить в карточку информацию о идиомах. Если фраза является идиомой, то в карточке есть пометка об этом

**Comment by annamaksimik** [comment]
📱 Mobile Final

_Watch frames "1.1 Vocabulary / ClickWord / Idiom", "1.1 Vocabulary / OpenWordCard / Idiom"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2329%3A1680

![image](https://user-images.githubusercontent.com/58423687/96880466-dd3e8500-1485-11eb-99ce-348ea7b7996f.png)

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]

_Watch frames "1366w  / 1.2 Vocabulary / СlickWord / Idiom", "1366w  / 1.2 Vocabulary / OpenWordCard / Idiom"_

**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2329%3A765

![image](https://user-images.githubusercontent.com/58423687/96881494-00b5ff80-1487-11eb-9548-c43111a54685.png)

**Comment by alexnpol** [comment]
@annamaksimik Около ссылки на источник добавить слово "Источник" / "Source"

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/97155945-1711d300-1787-11eb-8072-bd3e7b2944b3.png)

![image](https://user-images.githubusercontent.com/58423687/97155889-06615d00-1787-11eb-9102-33d6e595cfe8.png)

![image](https://user-images.githubusercontent.com/58423687/97155841-f47fba00-1786-11eb-85d2-e2a4b154e067.png)
