### ISSUE TITLE
Fix the ability to add a word to the dictionary indefinitely

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#131]
Description:
User can add one word to Vocabulary an unlimited number of times.

Solution:
Remove the ability to add the same word to the dictionary. That plus turned into a tick

link to the bug https://drive.google.com/file/d/1vOkSh0wQ_O1k4_mp6ednUiRxxBHpDpko/view?usp=sharing

**Comment by pavladan** [comment]
Fixed with detecting that a word has already been added to the dictionary in subtitles #80
