### ISSUE TITLE
[4h]Fix the button click notification window

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#133]
Description:
The notification window occupies most of the window. 

Solution:
- [x] Make the window compact. 
- [x] Also make a sketch of the notification window for clicking the repeat button

![image](https://user-images.githubusercontent.com/70699061/96559892-45df0380-12c6-11eb-9c19-da066f42bb3f.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final

Slow Repeat 
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2244%3A23057
![image](https://user-images.githubusercontent.com/58423687/96598556-a76b9600-12f7-11eb-98e9-ba4e98df56c4.png)


Repeat 
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2244%3A23063
![image](https://user-images.githubusercontent.com/58423687/96598642-c0744700-12f7-11eb-95b2-dda37d0759d5.png)

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]

Slow Repeat 
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2244%3A23057
![image](https://user-images.githubusercontent.com/58423687/96599216-5c9e4e00-12f8-11eb-83a6-33738b85461d.png)




Repeat 
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2244%3A23440
![image](https://user-images.githubusercontent.com/58423687/96599129-455f6080-12f8-11eb-89a7-66b5285b51d9.png)
