### ISSUE TITLE
[3h]Implement a new version of the eLangTV home page for b-testing

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#167]
Description:  Develop a different version of the elangtv home page. 

- [x] @lllana Provide Analytics data and suggestions for the home page
- [x] @NikaPipchenko UX/UI design
- [x] @annamaksimik  UI designe
- [x]  the implementation of the website

**Comment by lllana** [comment]
Analytics data from ad campaign:

- brief outcomes and effectiveness of the hypotheses - in [the file ](https://docs.google.com/spreadsheets/d/1Oaj3ZvPIm4x-8_lEEXXI5iLggTBPszDaqZT1LCIyu3w/edit?usp=sharing)

- user flow analysis + data on clicks per screens - in [the file ](https://www.figma.com/file/Xsqauv2HCM5mR5ARMAdTG2/Analytics_UF-eLangTV?node-id=2%3A2)

**Comment by lllana** [comment]
@AndrewVolosevich analytics part of the task is assign on me - don't worry))

**Comment by lllana** [comment]
A meeting need to be organised based on analytics done

**Comment by alexnpol** [comment]
Внести измененич для страницы:
- Изменить заглавие на стартовой странице, на заглавие с призывом к поиску (для призыва можно использовать стрелки и любые др. дизайнерские решения)
- Разместить теги в других местах (Красота - переместить во 2 строку справа, Здоровая еда поменять местами с Пранки, Музыка переместить во сторую строку центр)
- Поиск бар: при нажатии на строку поиска, окно поиска становится белым.

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/AuSthOYyxk2ixADgRtSt8B/?node-id=7%3A105

**Comment by alexnpol** [comment]
@NikaPipchenko 
- Change the title
- Fix a duplicate tag
![image](https://user-images.githubusercontent.com/70699061/97472222-a7ecd800-195a-11eb-8d85-bb819214a1a3.png)

**Comment by NikaPipchenko** [comment]
@alexnpol the issue with duplicate tag is fixed

**Comment by annamaksimik** [comment]
**Figma** https://www.figma.com/file/AuSthOYyxk2ixADgRtSt8B/UI?node-id=62%3A0

![image](https://user-images.githubusercontent.com/58423687/97845543-bdb52100-1cfd-11eb-8e5c-2d161e36bd15.png)
