### ISSUE TITLE
[8h]Change tooltips in elangTV

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#172]
Description: 
Add new and delete old tooltips in eLangTV

Delete tooltips marked with a red line in the image. Add tooltips marked with a yellow line

https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=1399%3A264
![image](https://user-images.githubusercontent.com/70699061/97268396-e7bd9d80-183c-11eb-827b-a5163fcfd2ad.png)

**Comment by annamaksimik** [comment]
🍰  Library
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=1399%3A2356
**[Tooltips.zip](https://github.com/easably/eLang-tv.com/files/5451926/Tooltips.zip)**
![image](https://user-images.githubusercontent.com/58423687/97437916-32224580-1935-11eb-9c28-dbe9134af301.png)

💻 HD Final [1366 width]
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=1399%3A2641
![image](https://user-images.githubusercontent.com/58423687/97437317-56315700-1934-11eb-88d2-a2003d150306.png)
