### ISSUE TITLE
[20m]Add back button

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#173]
Description:
Add a button that allows the user to navigate Back (to the previous page)

https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=1488%3A16532

![image](https://user-images.githubusercontent.com/70699061/97289214-f36a8d80-1857-11eb-9f1f-21365ea9bab3.png)

**Comment by lllana** [comment]
### Proved with Analytics

During Ad campaign there were 23 click on logo which is linked to the main page (current version has no functionality to make a step back) 
<img width="613" alt="Screenshot 2020-10-27 at 14 02 03" src="https://user-images.githubusercontent.com/61696166/97312164-18153400-185d-11eb-8313-a468df10a4d1.png">

**Comment by alexnpol** [comment]
@AndrewVolosevich  Кнопка работает исправно. Нужно сделать ё чуть больше 
![image](https://user-images.githubusercontent.com/70699061/97699561-658edc80-1abb-11eb-9c06-bc978d2291a4.png)
