### ISSUE TITLE
[8h]To create a window with a congratulation about registration

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#175]
Description: 
A window with the message "you are registered" appears after registration.

The window can display information about:
limits for adding words
"Start" button, which leads to the start page of eLangTV

**Comment by annamaksimik** [comment]
📱 Mobile Final
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2602%3A36


💻 HD Final [1366 width]
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2602%3A369


![image](https://user-images.githubusercontent.com/58423687/98225206-7e890900-1f65-11eb-8045-74d7479d008b.png)

![image](https://user-images.githubusercontent.com/58423687/98225239-8b0d6180-1f65-11eb-9b2e-4451deb7abfc.png)

**Comment by alexnpol** [comment]
Examples of pop-up about successful registration
![image](https://user-images.githubusercontent.com/70699061/98243701-62926100-1f7f-11eb-85e6-b3dd65fdf430.png)
![image](https://user-images.githubusercontent.com/70699061/98243713-66be7e80-1f7f-11eb-8348-4dd2f6d6127e.png)

**Comment by alexnpol** [comment]
![image](https://user-images.githubusercontent.com/70699061/98248190-a720fb00-1f85-11eb-9444-1b98e05776a3.png)

**Comment by annamaksimik** [comment]
@alexnpol 
Если будем использовать иллюстрации кота в инструкции, можно сделать такие рисуночки 
![image](https://user-images.githubusercontent.com/58423687/98927184-42b3ed80-24e9-11eb-81a4-cede0c25b756.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/98927789-0cc33900-24ea-11eb-9115-a8b3383c450b.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/98939674-d510bd00-24fa-11eb-8236-ac1c518de2d8.png)

**Comment by annamaksimik** [comment]
**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2804%3A726

![image](https://user-images.githubusercontent.com/58423687/98940500-21103180-24fc-11eb-83d0-5db4b6203c41.png)

**Comment by alexnpol** [comment]
- [ ] Arrange the text in 2 lines

![image](https://user-images.githubusercontent.com/70699061/99441930-a72bde00-2929-11eb-83a4-da27aa311697.png)

![image](https://user-images.githubusercontent.com/70699061/99442012-c6c30680-2929-11eb-9357-0a743ddc8b84.png)
