### ISSUE TITLE
Create a list of questions for usability testing eLangTV [1h]

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#177]
Description: create a Google Doc that contains questions for usability testing. The list should contain questions about how the user learned English, what applications they use, and so on. Add a question about eLangTV

**Comment by NikaPipchenko** [comment]
https://drive.google.com/file/d/1CYRcxR9FulkJf7yMm_XppR6huMmKDfSR/view?usp=sharing
