### ISSUE TITLE
[1h]Create intermediate Windows for the My vocabulary tab

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#178]
Description: 
Сreate 2 intermediate Windows for My vocabulary:
1. for the unregistered user to log in to my vocabulary
- A window with a message that the user does not have words, but they can add them after registration by viewing the video and clicking on the word. Add illustrations add a word

2. for a registered user who entered an empty my vocabulary
- a window with information about how the user can add a word to the vocabulary. Add an illustration of adding a word to the dictionary

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/AuSthOYyxk2ixADgRtSt8B/UI?node-id=85%3A19

![image](https://user-images.githubusercontent.com/72601980/97973097-9aaa7000-1dd6-11eb-86c7-a5883a526c55.png)
