### ISSUE TITLE
[2h] Remove broken links from the landing page easylang.app

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#185]
Description:
После общения с Сашей СЕО были замечены много старых страницы сайта с ошибкой 404. Их необходимо удалить

Ссылка на сайт: https://easylang.app/

**Comment by lllana** [comment]
<img width="585" alt="Screenshot 2020-10-28 at 17 02 01" src="https://user-images.githubusercontent.com/61696166/97470315-4ec37b00-193f-11eb-8990-bb8fe3b0c502.png">
we checked how Goоgle search engine indexed our web pages and found links with 404 error on them 
after 

- link № 4
- link № 5
- link № 9
- link № 10
- link № 11
- link № 12
- link № 13
- link № 14

Please, check other pages
