### ISSUE TITLE
make a relevant selection of videos in accordance with the target audience and market

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/eLang-tv.com#2]
Description:
when you first open the web player, a window opens with video search and selection
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=581%3A196
Expected behaviour:
make a relevant selection of videos in accordance with the target audience and market

**Comment by lllana** [comment]
Tags:

1. Healthy food
2. Beauty 
3. Sport 
4. Technologies
5. Video Games
6. Fun 
7. English 
8. Cars
9. Do it yourself 
10. Learn 
11. Bloggers
12. News
13.
