### ISSUE TITLE
Replace text in ad layouts

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#215]
Description:
Replace the text in ad layouts. You can find the text in the chat using ad layouts

**Comment by annamaksimik** [comment]
_**Archiver**    [AD.zip](https://github.com/easably/eLang-tv.com/files/5486653/AD.zip)_


![image](https://user-images.githubusercontent.com/58423687/98091000-d8220280-1e95-11eb-8e8e-29ba41e389c1.png)
![image](https://user-images.githubusercontent.com/58423687/98091050-e8d27880-1e95-11eb-9323-a5b636a65942.png)
