### ISSUE TITLE
Create a cover for a video (elangTV channel)

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#242]
Description: create an image that will be the cover of a video on our YouTube channel. Dimensions for the image see the photo below:

![image](https://user-images.githubusercontent.com/70699061/98777174-53893400-2401-11eb-9235-4b0930f2c798.png)

**Comment by annamaksimik** [comment]
**Архив** [Cover Video_YouTube.zip](https://github.com/easably/eLang-tv.com/files/5572857/Cover.Video_YouTube.zip)
**Figma** https://www.figma.com/file/9buIqjncdH6rYRhcZzncnu/Youtube-Channel-Template-Community?node-id=47%3A21
![image](https://user-images.githubusercontent.com/58423687/99789429-9fd82080-2b33-11eb-85e5-ec45032f8ba8.png)
