### ISSUE TITLE
Change the spelling of the "log in" buttons"

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#243]
Description:
you need to correct inaccuracies in the button spelling.

Login - "Вход" (существительное) - подходит для названия окна, раздела
Log in - "Войти" (глагол) - подходит для названия кнопки действия

- [x] https://www.elang-tv.com/auth
![image](https://user-images.githubusercontent.com/70699061/98778503-86342c00-2403-11eb-8d19-2b2f9a7d8ac7.png)

**Comment by alexnpol** [comment]
- [ ] https://elang-tv.herokuapp.com/auth

![image](https://user-images.githubusercontent.com/70699061/98850971-9fba8f80-2466-11eb-8bc7-d520ef87fd19.png)

- [ ] https://elang-tv.herokuapp.com/vocabulary
![image](https://user-images.githubusercontent.com/70699061/98851059-c1b41200-2466-11eb-8557-66691dc708f7.png)

**Comment by alexnpol** [comment]
- [ ]  Мобильная версия Словаря для незарегистрированного пользователя

![image](https://user-images.githubusercontent.com/70699061/98851538-74847000-2467-11eb-8dd6-00ad30ff52bd.png)

**Comment by alexnpol** [comment]
Последние три пункта не выполнены: Log In раздельно

**Comment by AndrewVolosevich** [comment]
Check on our current dev on https://dev-elang-tv-shi2q.ondigitalocean.app/
