### ISSUE TITLE
[3h] Replace the information in the pop up about the need to register in the extension[1h]

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#244]
Description:
Change the pop-up information according to the layouts in Figma

![image](https://user-images.githubusercontent.com/70699061/98807071-2d788980-242b-11eb-8734-4a56f7f1f970.png)

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/IKc3yczU3iBtfhFykYyf66/eLang-Extension?node-id=725%3A927
