### ISSUE TITLE
Add tags to the layout that are already on the site

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#245]
Description:
The site has tags that are not available for layouts (HD, mobile).

- [ ] Add tags to the layout:
 Netflix
TED

- [ ] Replace the FUN tag with the Pranks tag.

![image](https://user-images.githubusercontent.com/70699061/98820720-97029300-243f-11eb-9360-3ae442905a51.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final **Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=658%3A35
💻 HD Final [1366 width] **Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2806%3A133

![image](https://user-images.githubusercontent.com/58423687/98948816-fb892500-2507-11eb-9475-8af0d44046cf.png)
![image](https://user-images.githubusercontent.com/58423687/98948914-1cea1100-2508-11eb-921e-b8221d05d654.png)
