### ISSUE TITLE
[8h]Make a pages "Error 404" and "No internet" with the cat Lenya

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#246]
Description:
Make a new page design Error 404. Add a cat to the page

![image](https://user-images.githubusercontent.com/70699061/98930866-52820080-24ee-11eb-8b7e-57995c4d6aa4.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/98957894-c209e700-2512-11eb-8c26-adf1b01cb710.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/99041316-bdd5dc00-259b-11eb-8f6d-2efe778ce776.png)

**Comment by alexnpol** [comment]
Вариант 3 больше подходт под страницу ошибки

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]

_**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2859%3A22_

![image](https://user-images.githubusercontent.com/58423687/99077088-45880e80-25cd-11eb-822a-c17cd603bd29.png)


📱 Mobile Final

_**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2845%3A0_

![image](https://user-images.githubusercontent.com/58423687/99077208-6fd9cc00-25cd-11eb-8a75-6640f057d15a.png)

**Comment by alexnpol** [comment]
- [ ] @AndrewVolosevich обсуди настройку аналитики для кнопок с @lllana 

![image](https://user-images.githubusercontent.com/70699061/99219993-d558d300-27ee-11eb-9c24-4409c1817233.png)

**Comment by alexnpol** [comment]
- [ ] На странице Ошибки 404 удалить точку и в русской версии прописная буква только первая в первом слове (остальные маленькие - касается только русской версии) 
![image](https://user-images.githubusercontent.com/70699061/99440509-ba3dae80-2927-11eb-85e0-67b504b48ea5.png)

**Comment by alexnpol** [comment]
- [ ] Точка не нужна
![image](https://user-images.githubusercontent.com/70699061/99441055-6e3f3980-2928-11eb-81ca-df3c1bdc359a.png)
