### ISSUE TITLE
Make changes to the authorization page

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#247]
Description:
make changes to the authorization page.

1. Change the text " or " To "Or Continue With" / "Или продолжить с:"
2. Change Google logo  (link on google logo https://www.figma.com/file/AuSthOYyxk2ixADgRtSt8B/UI?node-id=257%3A54)

![image](https://user-images.githubusercontent.com/70699061/98934967-ddb1c500-24f3-11eb-918e-bcb1297aaa46.png)

**Comment by NikaPipchenko** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/72601980/98949964-74d54780-2509-11eb-95d7-8c221ff9a511.png)
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=1495%3A1089

**Comment by NikaPipchenko** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/72601980/98951108-e9f54c80-250a-11eb-9684-3c90de882166.png)
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2602%3A369

**Comment by NikaPipchenko** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/72601980/98952240-473dcd80-250c-11eb-809e-768b8b6317ea.png)

https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2602%3A369

**Comment by alexnpol** [comment]
- [ ] Удалить "а" в тексте кнопки
![image](https://user-images.githubusercontent.com/70699061/99442317-451fa880-292a-11eb-9f96-d9f1ca42776b.png)

**Comment by alexnpol** [comment]
- [ ] Добавить расстояние между текстом и кнопками.
Ссылка на макет в фигме https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2602%3A369
Ссылка на страницу, где произвести правки https://dev-elang-tv-shi2q.ondigitalocean.app/auth

![image](https://user-images.githubusercontent.com/70699061/99442929-1fdf6a00-292b-11eb-97e0-029da78ce972.png)
