### ISSUE TITLE
[1h]Make the main page of elang-TV in the b-page style

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#248]
Description:
Make the main page of elang-TV in the b-page style as the b-page for advertising. Screen of page b:

![image](https://user-images.githubusercontent.com/70699061/98945757-004bda00-2504-11eb-9d99-906d585e48c5.png)

**Comment by annamaksimik** [comment]
📱 Mobile Final **Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=658%3A35
💻 HD Final [1366 width] **Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2806%3A133

![image](https://user-images.githubusercontent.com/58423687/98948816-fb892500-2507-11eb-9475-8af0d44046cf.png)
![image](https://user-images.githubusercontent.com/58423687/98948914-1cea1100-2508-11eb-921e-b8221d05d654.png)

**Comment by alexnpol** [comment]
В русской версии должен быть хаголовок "Английский с удовольствием" https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2926%3A30335

 Сейчас там вот так:
![image](https://user-images.githubusercontent.com/70699061/100540850-030f3480-3251-11eb-853a-3e4ad33073f1.png)
