### ISSUE TITLE
Change the list of tags on the elangTV page

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#253]
The last advertising experiment showed that some ads are not interesting to users. We decided to delete some of the tags and leave only:
Английский / English, 
Технологии / Technology,  
здоровая еда /Healthy food, 
TED, 
Машины / Cars (search for a more specific topic), 
Путешествия / Travel,
Музыка / Music, 
Мультфильмы / Cartoons, 
TV Series (English serial)

- [x] Delete unnecessary tags

- [x] Group tags by color

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/99409127-1988c800-2902-11eb-9b4c-d16fb02d5523.png)

**Comment by annamaksimik** [comment]
💻 HD Final [1366 width]
_**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2806%3A133_

📱 Mobile Final
_**Figma** https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=658%3A35_



![image](https://user-images.githubusercontent.com/58423687/99409934-f579b680-2902-11eb-9d5b-481f22b32179.png)
