### ISSUE TITLE
Add the ability to contact support in the extension window [45 min]

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#258]
Description:
the User should be given the opportunity to provide feedback. To do this, add the (example Support) button in the extension window

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/IKc3yczU3iBtfhFykYyf66/eLang-Extensione?node-id=1447%3A243
![Screenshot_9](https://user-images.githubusercontent.com/72601980/99944838-a14c5780-2d84-11eb-8b58-21a9d9fbafda.png)
