### ISSUE TITLE
[⏳ 4h]Analyze competitors by the home page criterion

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#269]
Description:
Make a document that will contain screenshots:
- the main pages of elang-tv competitors
- educational platforms (courses, etc.)

First of all it is interesting to display the side menu on desktop. 

Need screenshots of the desktop and mobile versions.

**Comment by annamaksimik** [comment]
https://www.figma.com/file/qul7HUgYGfjCueVIlitLQm/Analyze-Lending?node-id=0%3A1
![image](https://user-images.githubusercontent.com/58423687/100717522-37a6fb80-33cb-11eb-9243-4737b33a6948.png)
