### ISSUE TITLE
Draw a layout to display the translation of the word "the"

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#276]
Make the "untranslatable article" sketch as in the extension

![image](https://user-images.githubusercontent.com/70699061/100738390-8ca43b00-33e6-11eb-926e-a04d2fe7b5a8.png)
![image](https://user-images.githubusercontent.com/70699061/100739843-c9713180-33e8-11eb-9fc4-acc052e844a8.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=3151%3A0
![image](https://user-images.githubusercontent.com/58423687/101177255-a6e54f80-3658-11eb-9db1-4b346783be2e.png)
