### ISSUE TITLE
Sort section by type search bar

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#280]
Description:
Arrange the sorting section as shown in the example image

![image](https://user-images.githubusercontent.com/70699061/100764272-37c4ec80-3407-11eb-9115-09c0149de723.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2763%3A51

![image](https://user-images.githubusercontent.com/58423687/101178648-4e16b680-365a-11eb-9b0e-47da732289cf.png)
