### ISSUE TITLE
Analyze your competitors on the start page [3h]

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#284]
Description:
You need to analyze what the competitors ' home page looks like. You are interested in the presence of a side menu, a search button, and other possible elements on the home page.

Elang-tv competitor analysis (screenshots+comments)

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/qul7HUgYGfjCueVIlitLQm/?node-id=114%3A219
