### ISSUE TITLE
State: what happens when the user runs out of limits (subscription in the future) [0,5h]

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#285]
Description:
will the user Receive a notification that they have run out of limits (subscription) and need to renew their premium account?

Discussion question.

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/?node-id=473%3A242

![image](https://user-images.githubusercontent.com/72601980/101017963-dd00d180-357b-11eb-8dea-ff9590f8cba1.png)

**Comment by NikaPipchenko** [comment]
![image](https://user-images.githubusercontent.com/72601980/101019326-dbd0a400-357d-11eb-9649-95ecfc4f9f34.png)
 

https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/Artifacts?node-id=499%3A40
