### ISSUE TITLE
Create a new user registration with a test subscription

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#289]
Description:
Draw a new version of the user's path from installing the extension to active use with a premium account.

The scheme should include:
- check-in option
- time of subscription
 is a trial period
- limitation of functionality after the trial period expires
- - purchase of a premium account (subscription renewal)

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/?node-id=473%3A242

![image](https://user-images.githubusercontent.com/72601980/101017900-c490b700-357b-11eb-8158-e0ebaf3663d2.png)
