### ISSUE TITLE
How the domain looks on YouTube and in our company

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/eLang-tv.com#290]
our company 
![Screenshot_1](https://user-images.githubusercontent.com/75259195/101021536-1720a200-3581-11eb-8f2d-2b1a0e9a41cf.png)
youtube 
![2](https://user-images.githubusercontent.com/75259195/101021603-29024500-3581-11eb-917d-32d75a8d517f.png)

**Comment by lllana** [comment]
https://elang-tv.herokuapp.com/ - is our Dev version
https://www.elang-tv.com/ - is our Prod version
