### ISSUE TITLE
[4h]To upload pictures in SVG

### ISSUE THREAD

**Issue by alexnpol** [easably/eLang-tv.com#293]
Description:
Upload these images in SVG format:
- all cats in pop up instructions https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2689%3A25356
- https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2793%3A30638
- https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2804%3A726
- https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2859%3A22
- https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=2859%3A146

Attach all images in the comments

**Comment by annamaksimik** [comment]
[instruction_eLang-TV.zip](https://github.com/easably/eLang-tv.com/files/5643228/instruction_eLang-TV.zip)
[eLang-TV.zip](https://github.com/easably/eLang-tv.com/files/5643229/eLang-TV.zip)

**Comment by alexnpol** [comment]
Этих котов вставить вместо тех, что в поп апах инструкции elangTV
