### ISSUE TITLE
[🤷‍♂️]first launch on heroku after clearing cache without fonts (ERR_ABORTED 500 (Internal Server Error))

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/eLang-tv.com#38]

**Comment by pavladan** [comment]
After the first launch or Hard Reload (Cmd + Shift + R) fonts are not loaded
![image](https://user-images.githubusercontent.com/44526604/94054569-7d03e700-fde4-11ea-9143-05104c79d3aa.png)
