### ISSUE TITLE
Add the ability that idiom will be highlighted automatically 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/eLang-tv.com#51]
Description:
During watching the video- the idioms and phraseological words will be highlighted with bottom line
Expected behavior:
There will be inability to turn this functional off

**Comment by EugeneShastak** [comment]
- [ ] @pavladan take design to work from [Figma](https://www.figma.com/file/0ypcnOEJn9iQVd5gNYROLG/eLang-TV?node-id=1145%3A0)
